### ISSUE TITLE
Bug: new API GetNearestLocationsRequest

### ISSUE THREAD

**Issue by 11mb** [DivideBV/Postnl#64] opened 2018-10-09 11:47 UTC
**Expected Behavior**

When calling `Postnl::getNearestLocations` I Expect a response with dropoff locations. 

**Current Behavior**

When executed, the response is an error:

    "Parameter 'Location.OpeningTime' may not be null."

**Steps to Reproduce**

    // Codesnippet from Postnl::getNearestLocations with sample data
    $message = new ComplexTypes\Message;
    $location = new ComplexTypes\Location('4330AB', 'false', '15-10-2018');
    $request = new ComplexTypes\GetNearestLocationsRequest($message, $location, 'NL');

**Workaround**

It looks like PostNL doesnt like the empty key `OpeningTime`. A Quick workaround is to disable line 24 in BaseLocation:

    /**
     * @var string
     */
    //protected $OpeningTime = null;

**Version**
v2.0.0-beta1

**Comment by CrazyHenk44** [comment] 2018-10-09 14:01
I can confirm this function is broken:
```
$locations = $client->getNearestLocations($zip, false, null, $country);
```
Results in errors:
- Parameter 'Location.AllowSundaySorting' may not be null.
- Parameter 'Location.OpeningTime' may not be null.

I tried to set it manually, but the same error.

**Comment by ameenross** [comment] 2018-10-09 14:57
This is the same for the [confirming webservice](https://github.com/DivideBV/Postnl/issues/63). They essentially changed the behaviour of the new endpoints, instead of just different authentication. I've already gotten an acknowledgement from PostNL in this regard.

**Comment by CrazyHenk44** [comment] 2018-10-09 15:06
Maybe, but getNearestLocations($zip, false, null, $country) sets AllowSundaySorting to false (2nd argument). So the error might indicate there is something broken in the library as well.

**Comment by ameenross** [comment] 2018-10-09 16:01
It should be a string "true"/"false". According to the WSDL, the value is simply a string.

**Comment by ameenross** [comment] 2018-10-09 16:02
However, looks like the OpeningTime error can't be solved, like #63

**Comment by 11mb** [comment] 2018-10-18 08:46
Isn't it possible to add the variables dynamicly to the class?

**Comment by ameenross** [comment] 2018-10-18 08:50
It would mean adding class annotation like `@property string $openingTime` and removing the properties. Not necessarily a big deal, but PostNL violates their WSDL so it's a won't fix.

Besides, I have no clue for how many properties I would need to do that

This has already cost us a lot of time.

**Comment by 11mb** [comment] 2018-10-18 12:48
Do you have contact about this issue with PostNL? Is there something I can support you with?

**Comment by ameenross** [comment] 2018-10-18 15:04
They acknowledged the issue and apparently they're working on it. I hope to hear news next week.

**Comment by ameenross** [comment] 2018-10-24 10:17
They made a new release last monday. This should be resolved. Can you test?

**Comment by CrazyHenk44** [comment] 2018-10-24 18:24
I can confirm it is fixed.

**Comment by ameenross** [comment] 2018-10-25 08:45
Great. Thanks for confirming

**Closed as completed by ameenross** 2018-10-25 08:45 UTC

**Comment by 11mb** [comment] 2018-10-25 12:14
Yes it is working indeed. Thanks for your effort @ameenross!
